Scriptify ingest_data node script
Use program/command to support script args and error logging.
```
ryanholinshead@Ryans-MacBook-Pro semantic-retrieval % npx ts-node examples/typescript/financial_report/ingest_data.ts -h
Usage: ingest_data [options]

Script to ingest 10k financial report documents into a Pinecone index and serialize associated metadata to disk

Options:
  -p, --pinecone_index [PINECONE_INDEX]  specify the name of the pinecone index to ingest the documents into (default: "test-financial-report")
  -h, --help                             display help for command
```

Removed all but 2 10k docs and ran the script:
```
ryanholinshead@Ryans-MacBook-Pro semantic-retrieval % npx ts-node examples/typescript/financial_report/ingest_data.ts
Starting ingestion...
Transformed 2 documents for ingestion
Persisted metadataDB to disk
NAMESPACE: beca28ba-8614-460a-9d97-79f8b9793277
Ingestion complete
Done!
```

Also ran with invalid indexName to ensure the arg is used and error propagates:
```
ryanholinshead@Ryans-MacBook-Pro semantic-retrieval % npx ts-node examples/typescript/financial_report/ingest_data.ts -p test
Starting ingestion...
Transformed 2 documents for ingestion
Persisted metadataDB to disk
NAMESPACE: 73552541-e9eb-447f-a548-98e28aa5f830
/Users/ryanholinshead/Projects/semantic-retrieval/node_modules/@pinecone-database/pinecone/dist/errors/handling.js:33
            op = body.call(thisArg, _);
                      ^
PineconeConnectionError: Request failed to reach Pinecone. Verify you have the correct environment, project id, and index name configured.
```